# Generated by Django 5.0.3 on 2024-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
